// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/pbjson/pbjsontest/test.proto

package pbjsontest // import "github.com/bitnami-labs/pbjson/pbjsontest"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestDefaults struct {
	AnExample            string   `protobuf:"bytes,1,opt,name=an_example,json=anExample" json:"an_example,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestDefaults) Reset()         { *m = TestDefaults{} }
func (m *TestDefaults) String() string { return proto.CompactTextString(m) }
func (*TestDefaults) ProtoMessage()    {}
func (*TestDefaults) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_2f5aa204712cd99c, []int{0}
}
func (m *TestDefaults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestDefaults.Unmarshal(m, b)
}
func (m *TestDefaults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestDefaults.Marshal(b, m, deterministic)
}
func (dst *TestDefaults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestDefaults.Merge(dst, src)
}
func (m *TestDefaults) XXX_Size() int {
	return xxx_messageInfo_TestDefaults.Size(m)
}
func (m *TestDefaults) XXX_DiscardUnknown() {
	xxx_messageInfo_TestDefaults.DiscardUnknown(m)
}

var xxx_messageInfo_TestDefaults proto.InternalMessageInfo

func (m *TestDefaults) GetAnExample() string {
	if m != nil {
		return m.AnExample
	}
	return ""
}

func init() {
	proto.RegisterType((*TestDefaults)(nil), "test.TestDefaults")
}

func init() {
	proto.RegisterFile("pkg/pbjson/pbjsontest/test.proto", fileDescriptor_test_2f5aa204712cd99c)
}

var fileDescriptor_test_2f5aa204712cd99c = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x28, 0xc8, 0x4e, 0xd7,
	0x2f, 0x48, 0xca, 0x2a, 0xce, 0xcf, 0x83, 0x52, 0x25, 0xa9, 0xc5, 0x25, 0xfa, 0x20, 0x42, 0xaf,
	0xa0, 0x28, 0xbf, 0x24, 0x5f, 0x88, 0x05, 0xc4, 0x56, 0xd2, 0xe5, 0xe2, 0x09, 0x49, 0x2d, 0x2e,
	0x71, 0x49, 0x4d, 0x4b, 0x2c, 0xcd, 0x29, 0x29, 0x16, 0x92, 0xe5, 0xe2, 0x4a, 0xcc, 0x8b, 0x4f,
	0xad, 0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x4c, 0xcc,
	0x73, 0x85, 0x08, 0x38, 0xd9, 0x44, 0x59, 0xa5, 0xe7, 0xeb, 0xe5, 0x25, 0xe6, 0x66, 0xea, 0x15,
	0x95, 0xe6, 0xe9, 0x97, 0xe4, 0xe7, 0xe7, 0x24, 0x67, 0x24, 0x66, 0xe6, 0xe9, 0x96, 0xa7, 0x26,
	0xe9, 0x63, 0xb5, 0xd2, 0x1a, 0xc1, 0x4c, 0x62, 0x03, 0xdb, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0x0f, 0xdd, 0xce, 0xb3, 0x9d, 0x00, 0x00, 0x00,
}
